bower.json
=> Updates to etools-app-selector v1.0.10

src/elements/common-elements/file-attachments-tab/file-attachments-tab.js, src/elements/core-elements/app-config/etools-app-config.html, src/elements/data-elements/update-visit-details-data.html, src/elements/data-elements/visit-info-data.html, src/elements/pages/visits-page-components/visits-info-view/visits-info-view-main/visits-info-view-main.html
=> Adds attachments onto the visit itself

src/elements/common-elements/assign-attachments/assign-attachments.html, src/elements/common-elements/assign-attachments/assign-attachments.js, src/elements/common-elements/assign-attachments/assign-attachments.scss, src/elements/common-elements/file-attachments-tab/file-attachments-tab.html, src/elements/common-elements/file-attachments-tab/file-attachments-tab.js, src/elements/core-elements/app-config/etools-app-config.html, src/elements/data-elements/initial-data.html, src/elements/pages/visits-page-components/action-points/action-points.js, src/elements/pages/visits-page-components/visits-info-view/visit-activity-elements/visit-activity-tab/visit-activity-tab.js, src/elements/pages/visits-page-components/visits-list-view/visits-list-view.html, src/elements/pages/visits-page-components/visits-list-view/visits-list-view.js
=> document type dropdown restrictions

src/elements/pages/visits-page-components/visits-list-view/visits-list-view.js
=> removes action pts from export list

src/elements/pages/visits-page-components/visits-info-view/visit-activity-elements/visit-activity-tab/visit-activity-tab.js
=> removes disabled cpoutputs

src/elements/data-elements/get-cp-outputs-data.html, src/elements/pages/visits-page-components/visits-info-view/visit-activity-elements/visit-activity-tab/visit-activity-tab.html, src/elements/pages/visits-page-components/visits-info-view/visit-activity-elements/visit-activity-tab/visit-activity-tab.js
=> shows all cp outputs when selected partner is government

src/elements/core-elements/app-main-header/app-main-header/app-main-header.html
=> Changes logout link to /logout

src/elements/core-elements/app-sidebar-menu/app-sidebar-menu.html
=> Updates info link on sidebar

src/elements/core-elements/app-config/etools-app-config.html, src/elements/data-elements/get-attachments.html
=> Visit tasks gov

src/elements/core-elements/app-config/etools-app-config.html, src/elements/core-elements/app-main-header/app-main-header/app-main-header.html
=> Adds env notification to remaining environments

src/elements/common-elements/search-and-filter-element/search-and-filter.html, src/elements/data-elements/initial-data.html
=> fix filter to not show when no filters adeded

package-lock.json, src/elements/common-elements/support-btn.html, src/elements/core-elements/app-main-header/app-main-header/app-main-header.html, src/index.html
=> [PROD] Support tool update

src/elements/core-elements/app-config/etools-app-config.html
=> remove trailing slash on attachments calls

src/elements/app-behaviors/query-params-controller.html, src/elements/common-elements/pages-header-element/pages-header-element.js, src/elements/common-elements/pages-header-element/pages-header-element.spec.html, src/elements/pages/partners-page-components/partners-list-view/partners-list-view.html
=> adds query params to export function

src/elements/data-elements/check-user-existence.html, src/elements/pages/visits-page-components/visits-list-view/visits-list-view.js
=> User exists errormessage

bower.json, src/elements/core-elements/app-shell-element/app-shell.html
=> Adds etools-piwik-analytics

src/elements/common-elements/share-documents/share-documents.js, src/elements/pages/visits-page-components/visits-info-view/visit-activity-elements/visit-activity-tab/visit-activity-tab.js
=> Attachment types new

src/elements/common-elements/search-and-filter-element/search-and-filter.html, src/elements/pages/visits-page-components/visits-list-view/visits-list-view.js
=> fix cp output blanks bug, adjust width of dropdowns

src/elements/common-elements/assign-attachments/assign-attachments.html, src/elements/core-elements/app-config/etools-app-config.html, src/elements/data-elements/get-attachments.html
=> adjust page-sizeall query to only happen on get

src/elements/core-elements/app-config/etools-app-config.html
=> Updates user endpoints

src/elements/common-elements/search-and-filter-element/search-and-filter.js, src/elements/data-elements/initial-data.html, src/elements/pages/visits-page-components/visits-list-view/visits-list-view.js
[ch10460]
adds offices to filters, removes partners without basic information from lists, removes api calls when filter type is selected
=> Offices filter

src/elements/pages/partners-page-components/partner-info-view/partner-staff-members-tab/partner-staff-members-tab.html
fixes labels lookup for tpm contact modal
=> adjust label lookup for tpm user addition

bower.json
=> Updates etools-profile-dialog to 2.0.9

src/elements/app-behaviors/activity-to-drd-value.html, src/elements/common-elements/assign-attachments/assign-attachments.html, src/elements/common-elements/assign-attachments/assign-attachments.js, src/elements/common-elements/file-attachments-tab/file-attachments-tab.html, src/elements/common-elements/file-attachments-tab/file-attachments-tab.js, src/elements/common-elements/share-documents/share-documents.js
=> v0 deprecation issues fix + share docs confirm disabled state updates

src/elements/common-elements/share-documents/share-documents.js
=> Fix share docs confirm btn disabled state

bower.json, src/elements/core-elements/app-main-header/app-main-header/app-main-header.html
=> Updates etools-app-selector to v1.1.10

bower.json
=> Updates app selector to v1.1.11

src/elements/data-elements/initial-data.html
=> fixes filters not loading for tpm user

bower.json
=> Upgrades etools-app-selector to v1.2.1

package-lock.json, src/elements/common-elements/file-attachments-tab/file-attachments-tab.js
=> [ch13372]Fix error on delete

src/elements/app-behaviors/query-params-controller.html, src/elements/app-behaviors/tests/query-params-controller.spec.html
=> adds tpm module to query string

bower.json
=> Upgrades app selector to 1.2.3

src/elements/core-elements/app-config/etools-app-config.html, src/elements/data-elements/initial-data.html, src/elements/pages/visits-page-components/visits-list-view/visits-list-view.js
[ch20342]Reduce functionality based on flag for FM
=> [ch20342]Reduce functionality based on flag for FM

src/elements/pages/visits-page-components/visits-list-view/visits-list-view.js
Added check for prp_server_on flag
=> Added check for prp_server_on flag

bower.json
=> [ch25846]Update app selector

src/elements/common-elements/support-btn.html
[ch26816] Update support link in header
=> [ch26816] Update support link in header

src/elements/common-elements/support-btn.html, src/index.html
=> [ch26829] Clean up index.html

.circleci/config.yml, bower.json, src/elements/core-elements/app-sidebar-menu/app-sidebar-menu.html
=> [ch29414]Update Implementation Intelligence link

src/elements/core-elements/app-sidebar-menu/app-sidebar-menu.html
=> [ch29414]Implem. Intell. link
